use database RETAIL360_DEMO;
use schema INGEST;


-- ROOT TASKS : RAW STREAM -> CLEAN PROCEDURE


create or replace task TSK_PROCESS_BRAND_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_BRAND_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_BRAND_STREAM();

create or replace task TSK_PROCESS_CATEGORY_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_CATEGORY_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_CATEGORY_STREAM();

create or replace task TSK_PROCESS_SUPPLIER_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_SUPPLIER_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_SUPPLIER_STREAM();

create or replace task TSK_PROCESS_STORE_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_STORE_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_STORE_STREAM();

create or replace task TSK_PROCESS_EMPLOYEE_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_EMPLOYEE_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_EMPLOYEE_STREAM();

create or replace task TSK_PROCESS_CUSTOMER_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_CUSTOMER_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_CUSTOMER_STREAM();

create or replace task TSK_PROCESS_CUSTOMER_ADDRESS_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_CUSTOMER_ADDRESS_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_CUSTOMER_ADDRESS_STREAM();

create or replace task TSK_PROCESS_PRODUCT_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_PRODUCT_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_PRODUCT_STREAM();

create or replace task TSK_PROCESS_PRODUCT_SKU_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_PRODUCT_SKU_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_PRODUCT_SKU_STREAM();

create or replace task TSK_PROCESS_PROMOTION_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_PROMOTION_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_PROMOTION_STREAM();

create or replace task TSK_PROCESS_PROMOTION_PRODUCT_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_PROMOTION_PRODUCT_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_PROMOTION_PRODUCT_STREAM();

create or replace task TSK_PROCESS_PROMOTION_STORE_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_PROMOTION_STORE_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_PROMOTION_STORE_STREAM();

create or replace task TSK_PROCESS_SALES_ORDER_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_SALES_ORDER_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_SALES_ORDER_STREAM();

create or replace task TSK_PROCESS_SALES_ORDER_LINE_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_SALES_ORDER_LINE_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_SALES_ORDER_LINE_STREAM();

create or replace task TSK_PROCESS_PAYMENT_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_PAYMENT_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_PAYMENT_STREAM();

create or replace task TSK_PROCESS_SHIPMENT_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_SHIPMENT_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_SHIPMENT_STREAM();

create or replace task TSK_PROCESS_RETURN_ORDER_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_RETURN_ORDER_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_RETURN_ORDER_STREAM();

create or replace task TSK_PROCESS_RETURN_ORDER_LINE_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_RETURN_ORDER_LINE_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_RETURN_ORDER_LINE_STREAM();

create or replace task TSK_PROCESS_PURCHASE_ORDER_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_PURCHASE_ORDER_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_PURCHASE_ORDER_STREAM();

create or replace task TSK_PROCESS_PURCHASE_ORDER_LINE_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_PURCHASE_ORDER_LINE_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_PURCHASE_ORDER_LINE_STREAM();

create or replace task TSK_PROCESS_INVENTORY_BALANCE_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_INVENTORY_BALANCE_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_INVENTORY_BALANCE_STREAM();

create or replace task TSK_PROCESS_INVENTORY_TXN_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_INVENTORY_TRANSACTION_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_INVENTORY_TRANSACTION_STREAM();

create or replace task TSK_PROCESS_CDC_RAW
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.RAW.STRM_CDC_EVENTS_SRC')
as
  call RETAIL360_DEMO.CLEAN.SP_PROCESS_CDC_EVENTS_STREAM();


-----------------------------------------------------------------------

alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_STORE_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_SKU_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_LINE_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PAYMENT_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_TXN_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CDC_RAW suspend;
alter task if exists RETAIL360_DEMO.INGEST.TSK_PROCESS_BRAND_RAW suspend;


select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_STORE_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_SKU_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_LINE_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_PAYMENT_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_TXN_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_CDC_RAW');



alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_BRAND_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CATEGORY_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SUPPLIER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_STORE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_EMPLOYEE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_ADDRESS_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_SKU_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PROMOTION_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PROMOTION_PRODUCT_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PROMOTION_STORE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_LINE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PAYMENT_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SHIPMENT_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_RETURN_ORDER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_RETURN_ORDER_LINE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PURCHASE_ORDER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PURCHASE_ORDER_LINE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_BALANCE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_TXN_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CDC_RAW resume;






