-- 3) CLEAN → CORE tasks

-- These tasks match the same style you used for RAW → CLEAN.

use database RETAIL360_DEMO;
use schema CORE;

create or replace task TSK_LOAD_DIM_CUSTOMER_CORE
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.CLEAN.STRM_CUSTOMER')
as
  call RETAIL360_DEMO.CORE.SP_LOAD_DIM_CUSTOMER_SCD2();

create or replace task TSK_LOAD_DIM_STORE_CORE
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.CLEAN.STRM_STORE')
as
  call RETAIL360_DEMO.CORE.SP_LOAD_DIM_STORE_SCD2();

create or replace task TSK_LOAD_DIM_PRODUCT_SKU_CORE
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.CLEAN.STRM_PRODUCT_SKU')
as
  call RETAIL360_DEMO.CORE.SP_LOAD_DIM_PRODUCT_SKU_SCD2();

create or replace task TSK_LOAD_FACT_SALES_ORDER_CORE
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.CLEAN.STRM_SALES_ORDER')
as
  call RETAIL360_DEMO.CORE.SP_LOAD_FACT_SALES_ORDER();

create or replace task TSK_LOAD_FACT_SALES_ORDER_LINE_CORE
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.CLEAN.STRM_SALES_ORDER_LINE')
as
  call RETAIL360_DEMO.CORE.SP_LOAD_FACT_SALES_ORDER_LINE();

create or replace task TSK_LOAD_FACT_PAYMENT_CORE
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.CLEAN.STRM_PAYMENT')
as
  call RETAIL360_DEMO.CORE.SP_LOAD_FACT_PAYMENT();

create or replace task TSK_LOAD_FACT_INVENTORY_TXN_CORE
  warehouse = RETAIL360_TASK_WH
  when system$stream_has_data('RETAIL360_DEMO.CLEAN.STRM_INVENTORY_TRANSACTION')
as
  call RETAIL360_DEMO.CORE.SP_LOAD_FACT_INVENTORY_TRANSACTION();


  -- 4) Resume CORE tasks

alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_CUSTOMER_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_STORE_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_PRODUCT_SKU_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_SALES_ORDER_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_SALES_ORDER_LINE_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_PAYMENT_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_INVENTORY_TXN_CORE resume;


