-----------------------------------------------------------------------

alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_STORE_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_SKU_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_LINE_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PAYMENT_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_TXN_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CDC_RAW suspend;
alter task if exists RETAIL360_DEMO.INGEST.TSK_PROCESS_BRAND_RAW suspend;


select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_STORE_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_SKU_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_LINE_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_PAYMENT_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_TXN_RAW');
select system$task_dependents_enable('RETAIL360_DEMO.INGEST.TSK_PROCESS_CDC_RAW');



alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_BRAND_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CATEGORY_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SUPPLIER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_STORE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_EMPLOYEE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_ADDRESS_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_SKU_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PROMOTION_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PROMOTION_PRODUCT_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PROMOTION_STORE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_LINE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PAYMENT_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SHIPMENT_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_RETURN_ORDER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_RETURN_ORDER_LINE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PURCHASE_ORDER_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PURCHASE_ORDER_LINE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_BALANCE_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_TXN_RAW resume;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CDC_RAW resume;




------------------------------------------------------------------------------------

-- 4) Resume CORE tasks

alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_CUSTOMER_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_STORE_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_PRODUCT_SKU_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_SALES_ORDER_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_SALES_ORDER_LINE_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_PAYMENT_CORE resume;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_INVENTORY_TXN_CORE resume;