-- 2) What to suspend
-- Suspend CORE tasks
alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_CUSTOMER_CORE suspend;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_STORE_CORE suspend;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_DIM_PRODUCT_SKU_CORE suspend;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_SALES_ORDER_CORE suspend;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_SALES_ORDER_LINE_CORE suspend;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_PAYMENT_CORE suspend;
alter task RETAIL360_DEMO.CORE.TSK_LOAD_FACT_INVENTORY_TXN_CORE suspend;
-- Suspend CLEAN tasks too

-- At least the ones relevant to the files you are about to upload.

-- Example:

alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CUSTOMER_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_STORE_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PRODUCT_SKU_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SALES_ORDER_LINE_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_PAYMENT_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_INVENTORY_TXN_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_CDC_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_RETURN_ORDER_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_RETURN_ORDER_LINE_RAW suspend;
alter task RETAIL360_DEMO.INGEST.TSK_PROCESS_SHIPMENT_RAW suspend;

-- If you want a fully controlled batch, suspend all relevant RAW→CLEAN and CLEAN→CORE tasks first.